<?php
$session = Mage::registry('enquiry_data');
	$data = $session->getReplyMessage();
	$status = 0;
	if(strlen($data) == '0')
	{
     $status = 1;
	}
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Enquiry Information') ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Status') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                      
					   <?php if($session->getStatusId()==0){ ?>
					   <?php echo "Not Replied" ?> 
					   <?php } else{ ?>
					   <?php echo "Replied" ?> 
					   <?php } ?>
					  
                    </td>
                    <td style="width: 100%;"></td>
                </tr>
				 <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Name') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                      <?php echo $session->getName() ?> 
                    </td>
                    <td style="width: 100%;"></td>
                </tr>
				 <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Email') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                      <?php echo $session->getEmail() ?> 
                    </td>
                    <td style="width: 100%;"></td>
                </tr>
				 <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Address') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                      <?php echo $session->getAddress() ?> 
                    </td>
                    <td style="width: 100%;"></td>
                </tr>
				 <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Telephone') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                      <?php echo $session->getTelephone() ?> 
                    </td>
                    <td style="width: 100%;"></td>
                </tr>
				 <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Comment') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                      <?php echo $session->getComment() ?> 
                    </td>
                    <td style="width: 100%;"></td>
                </tr>
				  <?php if($status){ ?>
				   <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Your Message') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
               	     <textarea name="reply_message" id="reply_message"   title="<?php echo $this->__('reply_message') ?>" class="input-text"></textarea> 
					
                    </td>
                    <td style="width: 100%;"></td>
                   </tr>
				 <?php } else{ ?>
				 <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Your Message') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
               	     <?php echo $session->getReplyMessage() ?> 					 
                    </td>
                    <td style="width: 100%;"></td>
                  </tr>
                <?php } ?>
		  </tbody>
        </table>
    </div>
</div>